#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x0992CD44

//What is the plugin's name (and version)?
#define PLUGIN_NAME "Smart Rally v1.3"
