#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x13CE1707

//What is the plugin's name (and version)?
#define PLUGIN_NAME "SCT Plugin v1.2"

//Custom plugin stuff
#define UPGRADE_THERMAL_SENSORS 20
#define UPGRADE_PRESCIENCE      41
#define UPGRADE_FIRST_AID_PACKS 45
#define IMAGE_STIM_PACKS_EFFECT 930
#define IMAGE_OCULAR_IMPLANTS_EFFECT 426
