#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0xF7367C21

//What is the plugin's name (and version)?
#define PLUGIN_NAME "AI Mineral Boost v0.2"

//Plugin module ID generated by MakeID.HTA (randomly generated)
#define SETTINGS_INI_ID 0x760D551A
#define SETTINGS_INI_FILENAME "AiResourceInflater.ini"
