#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x1B4D69B6

//What is the plugin's name (and version)?
#define PLUGIN_NAME "General Plugin Template Project v2.38"

#define UPGRADE_BATTLECRUISER_SPEED 45
#define UPGRADE_ARBITER_ATTK_SPEED  46
#define UPGRADE_TERRAN_BLDG_ARMOR   58
#define UPGRADE_FIREBAT_BLUE_FLAME  59
