#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0xF18A197A

//What is the plugin's name (and version)?
#define PLUGIN_NAME "Burning Ground Plugin"
