#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x13CE1707

//What is the plugin's name (and version)?
#define PLUGIN_NAME "SCT Plugin v1.22"

//Custom plugin stuff
#define UNIT_FIEND              32
#define UNIT_DEEP_WARREN        145

#define WEAPON_TELEPATHIC_TRACE     56
#define WEAPON_CARNIVOROUS_MITES    57
#define WEAPON_MEDIATION_FIELD      77
#define WEAPON_MEDIATION_FIELD_HERO 78
#define WEAPON_OCULAR_IMPLANTS      107

#define UPGRADE_THERMAL_SENSORS 20
#define UPGRADE_PARTICLE_FILTER 35
#define UPGRADE_CONCENTRATED_PAYLOAD 36
#define UPGRADE_PRESCIENCE      41
#define UPGRADE_FIRST_AID_PACKS 45

#define TECH_TELEPATHIC_TRACE   18
#define TECH_OCULAR_IMPLANTS    30

#define IMAGE_STIM_PACKS_EFFECT       970
#define IMAGE_OCULAR_IMPLANTS_EFFECT  971
#define IMAGE_NEXUS_ATTACK_OVERLAY    972
