#pragma once

//For use in C-strings
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x1B4D69B6

//What is the plugin's name (and version)?
#define PLUGIN_NAME "Guts and Maggots plugin v0.1"

//익스트랙터에서 매초마다 제공하는 자원의 양
#define EXTRACTOR_MINERALS      6
#define EXTRACTOR_GAS           3
