#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x1B4D69B6

//Plugin module ID generated by MakeID.HTA (randomly generated)
#define SETTINGS_INI_ID 0x760D551A

//What is the plugin's name (and version)?
#define PLUGIN_NAME "General Plugin Template Project v2.37"
