#pragma once

//What is the plugin's ID?
//Plugin ID generated by MakeID.HTA (based on CRC32)
#define PLUGIN_ID 0x1B4D69B6

//What is the plugin's name (and version)?
#define PLUGIN_NAME "General Plugin Template Project v2.38"

#define UNIT_KUKULZA_COCOON         182

#define UPGRADE_BATTLECRUISER_SPEED 45
#define UPGRADE_ARBITER_ATTK_SPEED  46
#define UPGRADE_SCIENCE_VESSEL_SIGHT 48
#define UPGRADE_ARBITER_WPN_RANGE   50
#define UPGRADE_LURKER_RANGE        55
#define UPGRADE_SCOUT_ENERGY        57
#define UPGRADE_TERRAN_BLDG_ARMOR   58
#define UPGRADE_FIREBAT_BLUE_FLAME  59

#define TECH_SCOUT_CLOAKING         35
